In [1]:
import numpy as np
import pandas as pd
import random

In [14]:
%%time
product = pd.DataFrame(list(range(1000, 9000, 1)),columns=['id']).reindex()

def product_name(id):
    return 'SKU' + str(id)


product_categories = [["Electronic", "Kitchen", "Books", "Clothing"], [.3, .25, .3, .15]]

def product_category(product_categories = product_categories):
    return np.random.choice(product_categories[0],p=product_categories[1])

def product_cost(category):
    if category == 'Electronic':
        return random.randint(50,100) + random.uniform(0, 1)
    elif category == 'Books' :
        return  random.randint(1,20) + random.uniform(0, 1)
    elif category == 'Kitchen' :
        return  random.randint(1,50) + random.uniform(0, 1)
    elif category == 'Clothing' :
        return  random.randint(5,55) + random.uniform(0, 1)
    else:
        return  random.randint(5,55) + random.uniform(0, 1)

sub_category = {
    
    'Electronic': ['Home Appliance','Laptop','Accessories','Mobile'],
    'Books': ['Action & Adventure', 'Biographies','Business and Economic','Science'],
    'Kitchen': ['Cookware','Cleaning Supplier','Home Decor'],
    'Clothing': ['Mens','Womens','kids']
}    

sub_category_probablity = {
       
    'Electronic': [0.3,0.3,0.2,0.2],
    'Books': [0.3,0.2,0.3,0.2],
    'Kitchen': [0.3,0.3,0.4],
    'Clothing': [0.3,0.3,0.4]
    
    
}


def category_name(category):
    if category == 'Electronic':
        return np.random.choice(sub_category['Electronic'], p=sub_category_probablity['Electronic'] )
    
    elif category == 'Books':
        return  np.random.choice(sub_category['Books'], p=sub_category_probablity['Books'] )

    elif category == 'Kitchen':
        return  np.random.choice(sub_category['Kitchen'], p=sub_category_probablity['Kitchen'] )
    
    else:
         return  np.random.choice(sub_category['Clothing'], p=sub_category_probablity['Clothing'] )
        
    
def product_price(prod_cost):
    return prod_cost *  random.uniform(2,3)


prod_color = [['read','blue','white','black','other'],[0.2,0.2,0.2,0.3,0.1]]

def product_color(prod_color=prod_color):
    return np.random.choice(prod_color[0],p=prod_color[1])

product['product_id'] = product.apply(lambda row: product_name(id=row['id']), axis =1 )
product['product_category'] = product.apply(lambda row: product_category(product_categories = product_categories), axis =1 )
product['product_subcategory'] = product.apply(lambda x: category_name (category= x['product_category']), axis =1 )
product['product_cost'] = product.apply(lambda x: product_cost(category= x['product_category']), axis = 1)
product['product_price'] = product.apply(lambda x: product_price(prod_cost= x['product_cost']), axis = 1)
product['product_color'] = product.apply(lambda row: product_color(prod_color = prod_color), axis =1 )
product.drop(columns=['id'],inplace=True)
product

Wall time: 858 ms

,product_id,product_category,product_subcategory,product_cost,product_price,product_color
0,SKU1000,Clothing,Womens,53.766345,113.694764,white
1,SKU1001,Electronic,Home Appliance,66.894677,144.517310,read
2,SKU1002,Electronic,Accessories,60.890297,137.524351,read
3,SKU1003,Electronic,Accessories,52.443547,144.114537,blue
4,SKU1004,Books,Biographies,2.737187,5.956984,read
...,...,...,...,...,...,...
7995,SKU8995,Books,Business and Economic,3.287533,9.408869,other
7996,SKU8996,Clothing,Womens,11.550114,34.020911,black
7997,SKU8997,Electronic,Home Appliance,64.683189,185.139386,read
7998,SKU8998,Electronic,Accessories,61.022239,172.300975,read
7999,SKU8999,Kitchen,Home Decor,36.672339,89.653507,black